services:
  - type: web
    name: budget-tracker-backend
    env: java
    buildCommand: cd springapp && mvn clean package -DskipTests
    startCommand: cd springapp && java -jar target/SpringBootEmp-0.0.1-SNAPSHOT.jar
    healthCheckPath: /actuator/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget-tracker-db
          property: connectionString
      - key: JAVA_OPTS
        value: "-Xmx512m"
      - key: SERVER_PORT
        value: "8080"

databases:
  - name: budget-tracker-db
    databaseName: budget_tracker
    user: budget_user