services:
  - type: web
    name: budget-tracker-backend
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/SpringBootEmp-0.0.1-SNAPSHOT.jar
    healthCheckPath: /actuator/health
    envVars:
      - key: JAVA_OPTS
        value: "-Xmx512m"
      - key: PORT
        value: "8080"

databases:
  - name: budget-tracker-db
    databaseName: budget_tracker
    user: budget_user